[colors]
[colors.primary]
background = "#00110b"
background.normalized = [0.000000, 0.066667, 0.043137]
foreground = "#e6f6f0"
foreground.normalized = [0.901961, 0.964706, 0.941176]
dim_foreground = "#2a7a65"
dim_foreground.normalized = [0.164706, 0.478431, 0.396078]

[colors.cursor]
text = "#00110b"
text.normalized = [0.000000, 0.066667, 0.043137]
cursor = "#00a86b"
cursor.normalized = [0.000000, 0.658824, 0.419608]

[colors.selection]
text = "#00110b"
text.normalized = [0.000000, 0.066667, 0.043137]
background = "#CCCC99"
background.normalized = [0.800000, 0.800000, 0.600000]

[colors.normal]
black = "#114b3b"
black.normalized = [0.066667, 0.294118, 0.231373]
red = "#ff3370"
red.normalized = [1.000000, 0.200000, 0.439216]
green = "#00a86b"
green.normalized = [0.000000, 0.658824, 0.419608]
yellow = "#cceee1"
yellow.normalized = [0.800000, 0.933333, 0.882353]
blue = "#006540"
blue.normalized = [0.000000, 0.396078, 0.250980]
magenta = "#C3FCB8"
magenta.normalized = [0.764706, 0.988235, 0.721569]
cyan = "#80d4b5"
cyan.normalized = [0.501961, 0.831373, 0.709804]
white = "#e6f6f0"
white.normalized = [0.901961, 0.964706, 0.941176]

[colors.bright]
black = "#2a7a65"
black.normalized = [0.164706, 0.478431, 0.396078]
red = "#ff3370"
red.normalized = [1.000000, 0.200000, 0.439216]
green = "#00a86b"
green.normalized = [0.000000, 0.658824, 0.419608]
yellow = "#cceee1"
yellow.normalized = [0.800000, 0.933333, 0.882353]
blue = "#006540"
blue.normalized = [0.000000, 0.396078, 0.250980]
magenta = "#C3FCB8"
magenta.normalized = [0.764706, 0.988235, 0.721569]
cyan = "#80d4b5"
cyan.normalized = [0.501961, 0.831373, 0.709804]
white = "#e6f6f0"
white.normalized = [0.901961, 0.964706, 0.941176]
